Highlight today in date picker
elementary/granite pull request #426
Opened 2020-09-04 18:32 UTC by sebastianlay

Fixes #384 and improves the styling of the date picker a bit.

Before:
![before](https://user-images.githubusercontent.com/2980983/92274493-e034e480-eedc-11ea-975b-528320cbca68.png)

After:
![after](https://user-images.githubusercontent.com/2980983/92274490-de6b2100-eedc-11ea-8813-04ad7aec2efa.png)

2020-11-04 20:06 UTC, meisenzahl approved these changes

2020-11-04 20:12 UTC, danrabbit requested changes
We shouldn't be embedding CSS here

2020-11-04 21:10 UTC, danrabbit commented
I've proposed styles for Gtk.Calendar here https://github.com/elementary/stylesheet/pull/878

2020-11-09 19:00 UTC, cassidyjames commented
So this is superseded by https://github.com/elementary/stylesheet/pull/878?

2020-11-18 01:59 UTC, danrabbit commented
@cassidyjames not completely. The part about marking Today is still relevant, but the styles should be removed

2020-11-18 02:01 UTC, danrabbit requested changes

2020-11-18 02:01 UTC, danrabbit commented on README.md
> +    sudo ninja install
This is intentional since ninja will use polkit. Please revert this

2020-11-18 02:01 UTC, danrabbit commented on lib/Widgets/DatePicker.vala
> +
Styles are accounted for in the system stylesheet already, so we shouldn't have them here

2020-11-18 02:01 UTC, danrabbit commented on lib/Widgets/DatePicker.vala
> +            else {
elementary code style is cuddled else
```suggestion
            } else {
```

2020-12-21 18:31 UTC, danrabbit commented
Gonna close this since there's been no response to code review for over a month. Please feel free to reopen if changes are made :)

2020-12-21 18:31 UTC, closed without merging