new markup tooltip with secondary string description
elementary/granite pull request #446
Opened 2020-12-11 12:48 UTC by andirsun

Is neccesary for new tooltip indicators prohject, instead use traditional gtk markup with pango. 
Example : https://github.com/elementary/wingpanel-indicator-nightlight/pull/75#issuecomment-742953423

2020-12-11 21:38 UTC, cassidyjames commented
Would it make sense to have `markup_accel_tooltip` use this method as well so we're not repeating the Pango formatting?

2020-12-11 22:12 UTC, andirsun commented
> Would it make sense to have `markup_accel_tooltip` use this method as well so we're not repeating the Pango formatting?

Something like ```markup_accel_tooltip``` would be a 3rth parameter as ```string subdescription`` ?`

2020-12-11 22:19 UTC, cassidyjames commented
@andirsun no, I mean like `markup_accel_tooltip` could now use `markup_tooltip_with_string` to build its markup instead of manually building the same Pango markup string in two places.

2020-12-11 22:21 UTC, andirsun commented
> @andirsun no, I mean like `markup_accel_tooltip` could now use `markup_tooltip_with_string` to build its markup instead of manually building the same Pango markup string in two places.

Ohh, okay then, let me work in this change.

2020-12-11 22:29 UTC, cassidyjames commented on lib/Widgets/Utils.vala
> +
Trying to think of better terminology here, plus a bit more fleshed out docs:

```suggestion
/**
 * Takes a context string and description and returns {@link Pango} markup for use in a {@link Gtk.Tooltip}.
 *
 * Example:
 *
 * Description
 * Context
 *
 * @param context a standard tooltip text string
 *
 * @param description a standard tooltip text string
 *
 * @return markup with the description label on one line and a the context on a new line
 */
 public static string markup_contextual_tooltip (string? context, string? description = null) {
    string[] parts = {};
    if (description != null && description != "") {
        parts += description;
    }

    if (context != null && context != "") {
        var secondary = "<small>%s</small>".printf (context);
        parts += secondary;
    }

    return string.joinv ("\n", parts);
}

```

2020-12-14 19:21 UTC, danrabbit requested changes
This seems like overkill for this purpose tbh. For the purposes of `markup_accel_tooltip`, it accepts an array of strings and has to transform them. But I don't really see what advantage adding a whole method here has over just adding:

`public const string TOOLTIP_CONTEXT_MARKUP  """<span weight="600" size="smaller" alpha="75%">%s</span>""";`

you've also lost a pretty significant portion of the formatting here

2020-12-14 19:33 UTC, andirsun commented
> This seems like overkill for this purpose tbh. For the purposes of `markup_accel_tooltip`, it accepts an array of strings and has to transform them. But I don't really see what advantage adding a whole method here has over just adding:
> 
> `public const string TOOLTIP_CONTEXT_MARKUP """<span weight="600" size="smaller" alpha="75%">%s</span>""";`
> 
> you've also lost a pretty significant portion of the formatting here

Sure!, Im going to return as before.

2020-12-14 22:04 UTC, cassidyjames commented
@danrabbit derp, you're smart. Yeah, just exposing a public constant to use with `printf` syntax makes sense to me since there's no extra transforming or anything happening.

2020-12-15 18:14 UTC, danrabbit commented
Hey @andirsun I went ahead and made a separate PR since it's a little difficult to explain what I meant here: https://github.com/elementary/granite/pull/447

2020-12-15 18:22 UTC, andirsun commented
> Hey @andirsun I went ahead and made a separate PR since it's a little difficult to explain what I meant here: #447

What about this PR then ?

2020-12-15 19:24 UTC, cassidyjames commented
@andirsun sorry for all the back-and-forth on this. Dan's PR makes sense and we should use that constant in the indicators for the tooltip text. Since that PR supersedes this one, I'm closing this. Thanks again for your work on this!

2020-12-15 19:24 UTC, closed without merging