Fix #378
elementary/granite pull request #480
Opened 2021-03-21 04:54 UTC by alainm23

![image](https://user-images.githubusercontent.com/33765137/111893880-07b05200-89d4-11eb-9099-19aae35bf819.png)

- Take the screenshot using the [wingpanel-notification close button style](https://github.com/elementary/wingpanel-indicator-notifications/blob/master/data/NotificationEntry.css#L27). We'll probably also have to update elementary-stylesheet

2021-04-06 23:23 UTC, hanaral commented
Noice, I think it goes far better with the elementary style, and doesn't take up needless space on something that self-dismisses anyway.

2021-04-06 23:50 UTC, hanaral reviewed
Might want to bump copyright while you're at it

2021-04-07 00:24 UTC, ryonakano reviewed
Not tested yet but leaving some nitpicking coding style review.

2021-04-07 00:24 UTC, ryonakano commented on lib/Widgets/Toast.vala
> +            close_revealer.transition_type = Gtk.RevealerTransitionType.CROSSFADE;
```suggestion
            var close_revealer = new Gtk.Revealer () {
                valign = Gtk.Align.START,
                halign = Gtk.Align.START,
                transition_type = Gtk.RevealerTransitionType.CROSSFADE
            };
```

2021-04-07 00:24 UTC, ryonakano commented on lib/Widgets/Toast.vala
> +            notification_eventbox.add (notification_overlay);
```suggestion
            var notification_eventbox = new Gtk.EventBox () {
                above_child = false
            };
            notification_eventbox.add_events (Gdk.EventMask.ENTER_NOTIFY_MASK | Gdk.EventMask.LEAVE_NOTIFY_MASK);
            notification_eventbox.add (notification_overlay);
```

2021-06-22 16:51 UTC, jeremypw requested changes
This PR does not seem to do the styling of the close button? When I tried it the close button was not in the required style so not really usable.  Other than that this, the code LGTM and works as expected.

Should this be blocked pending amendments to the stylesheet being merged?

2021-07-26 15:59 UTC, hanaral commented
@alainm23 Any chance you could try fix the problem so it can be merged?

2024-10-09 20:22 UTC, alainm23 commented
I have another idea in mind for Granite.Toast, I'll close this for now.

2024-10-09 20:22 UTC, closed without merging